#!/usr/bin/env bash
# OpenTree Bot Runner Wrapper
# Generated by: opentree init
# Home: {{opentree_home}}
#
# Features:
#   - Auto-restart on crash (non-zero exit)
#   - Watchdog: kills bot when heartbeat goes stale
#   - Crash loop protection: cooldown after repeated rapid crashes
#   - Network check: waits for DNS before (re)starting
#   - PID file for external monitoring
#   - Clean shutdown via SIGTERM/SIGINT forwarding
#
# Exit code convention:
#   0  = Clean exit (no restart)
#   42 = Permanent stop ("opentree shutdown" command) -> no restart
#   *  = Crash -> restart after delay

set -euo pipefail

# ---- Configuration ----

OPENTREE_HOME="{{opentree_home}}"
BOT_CMD=(opentree start --mode slack --home "$OPENTREE_HOME")
DATA_DIR="$OPENTREE_HOME/data"
PID_FILE="$DATA_DIR/bot.pid"
HEARTBEAT_FILE="$DATA_DIR/bot.heartbeat"
LOG_DIR="$DATA_DIR/logs"

# Exit code for permanent stop (no restart)
EXIT_PERMANENT=42

# Watchdog settings
WATCHDOG_TIMEOUT=120          # seconds without heartbeat -> kill
WATCHDOG_INTERVAL=30          # check frequency (seconds)
WATCHDOG_INIT_DELAY=30        # grace period for bot to initialize
WATCHDOG_SIGKILL_WAIT=40      # seconds after SIGTERM before SIGKILL

# Crash loop protection
MAX_CRASHES=5                 # max crashes within CRASH_WINDOW
CRASH_WINDOW=600              # detection window (seconds)
COOLDOWN=300                  # cooldown duration after crash loop detected

# Network check
DNS_HOST="slack.com"
DNS_TIMEOUT=60                # max seconds to wait for DNS
DNS_CHECK_INTERVAL=5          # seconds between DNS attempts

# ---- Functions ----

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

dns_resolve() {
    # Attempt DNS resolution using the best available tool.
    # Supports: host, getent, nslookup, ping (fallback chain for minimal containers).
    if command -v host &>/dev/null; then
        host "$DNS_HOST" >/dev/null 2>&1
    elif command -v getent &>/dev/null; then
        getent hosts "$DNS_HOST" >/dev/null 2>&1
    elif command -v nslookup &>/dev/null; then
        nslookup "$DNS_HOST" >/dev/null 2>&1
    else
        ping -c 1 -W 3 "$DNS_HOST" >/dev/null 2>&1
    fi
}

check_network() {
    # Wait for DNS resolution to succeed before starting the bot.
    # Returns 0 on success, 1 on timeout.
    local elapsed=0
    while ! dns_resolve; do
        if [ $elapsed -ge $DNS_TIMEOUT ]; then
            log "ERROR: DNS check for $DNS_HOST failed after ${DNS_TIMEOUT}s"
            return 1
        fi
        log "Waiting for network... (${elapsed}s/${DNS_TIMEOUT}s)"
        sleep $DNS_CHECK_INTERVAL
        elapsed=$((elapsed + DNS_CHECK_INTERVAL))
    done
    [ $elapsed -gt 0 ] && log "Network restored (waited ${elapsed}s)"
    return 0
}

start_watchdog() {
    # Background process that monitors the heartbeat file.
    # If the heartbeat timestamp goes stale, sends SIGTERM to the bot,
    # then SIGKILL if it doesn't exit within WATCHDOG_SIGKILL_WAIT.
    (
        # Grace period: let the bot initialize and write first heartbeat
        sleep $WATCHDOG_INIT_DELAY

        while true; do
            sleep $WATCHDOG_INTERVAL

            # Read PID from file (bot.py writes this)
            local bot_pid
            bot_pid=$(cat "$PID_FILE" 2>/dev/null | tr -d '[:space:]')

            # Skip if PID is empty or not a number
            if [ -z "$bot_pid" ] || ! echo "$bot_pid" | grep -qE '^[0-9]+$'; then
                continue
            fi

            # If bot process is gone, watchdog exits
            if ! kill -0 "$bot_pid" 2>/dev/null; then
                break
            fi

            # If heartbeat file doesn't exist yet, skip (don't kill)
            if [ ! -f "$HEARTBEAT_FILE" ]; then
                continue
            fi

            # Read heartbeat timestamp (Unix epoch written by receiver)
            local last_beat
            last_beat=$(cat "$HEARTBEAT_FILE" 2>/dev/null | tr -d '[:space:]')
            if ! echo "$last_beat" | grep -qE '^[0-9]+$'; then
                continue
            fi

            # Check staleness
            local now age
            now=$(date +%s)
            age=$((now - last_beat))

            if [ "$age" -gt "$WATCHDOG_TIMEOUT" ]; then
                log "WATCHDOG: Heartbeat stale (${age}s > ${WATCHDOG_TIMEOUT}s), sending SIGTERM to PID $bot_pid"
                kill -TERM "$bot_pid" 2>/dev/null

                # Poll for process exit (every 2s, up to WATCHDOG_SIGKILL_WAIT)
                local wait_count=0
                local max_polls=$((WATCHDOG_SIGKILL_WAIT / 2))
                while [ $wait_count -lt $max_polls ]; do
                    sleep 2
                    if ! kill -0 "$bot_pid" 2>/dev/null; then
                        log "WATCHDOG: Process exited after SIGTERM (waited $((wait_count * 2))s)"
                        break
                    fi
                    wait_count=$((wait_count + 1))
                done

                # Force kill if still alive
                if kill -0 "$bot_pid" 2>/dev/null; then
                    log "WATCHDOG: SIGTERM ineffective after ${WATCHDOG_SIGKILL_WAIT}s, sending SIGKILL"
                    kill -9 "$bot_pid" 2>/dev/null
                fi

                break
            fi
        done
    ) &
    WATCHDOG_PID=$!
    log "Watchdog started (PID: $WATCHDOG_PID, timeout: ${WATCHDOG_TIMEOUT}s)"
}

stop_watchdog() {
    if [ -n "${WATCHDOG_PID:-}" ] && kill -0 "$WATCHDOG_PID" 2>/dev/null; then
        kill "$WATCHDOG_PID" 2>/dev/null || true
        wait "$WATCHDOG_PID" 2>/dev/null || true
        WATCHDOG_PID=""
        log "Watchdog stopped"
    fi
}

cleanup() {
    # Trap handler for SIGTERM/SIGINT.
    # Forwards signal to bot, waits for exit, then cleans up watchdog.
    log "Received shutdown signal, forwarding to bot..."

    if [ -n "${BOT_PID:-}" ] && kill -0 "$BOT_PID" 2>/dev/null; then
        kill -TERM "$BOT_PID" 2>/dev/null || true
        local count=0
        while [ $count -lt 40 ] && kill -0 "$BOT_PID" 2>/dev/null; do
            sleep 1
            count=$((count + 1))
        done
        if kill -0 "$BOT_PID" 2>/dev/null; then
            log "Bot did not exit after 40s, sending SIGKILL"
            kill -9 "$BOT_PID" 2>/dev/null || true
        fi
        wait "$BOT_PID" 2>/dev/null || true
    fi

    stop_watchdog
    rm -f "$PID_FILE"
    log "Shutdown complete"
    exit 0
}

# ---- Main ----

trap cleanup SIGTERM SIGINT
trap 'stop_watchdog' EXIT

mkdir -p "$LOG_DIR" "$DATA_DIR"

# -- Singleton lock: prevent multiple wrappers from running concurrently --
LOCK_FILE="$DATA_DIR/wrapper.lock"
exec 200>"$LOCK_FILE"
if ! flock -n 200; then
    log "ERROR: Another wrapper is already running (lock: $LOCK_FILE). Exiting."
    exit 1
fi
# Lock held on fd 200 until script exits (auto-released on crash/SIGKILL too)

# -- Stale process cleanup: kill orphaned bot from previous run --
if [ -f "$PID_FILE" ]; then
    stale_pid=$(cat "$PID_FILE" 2>/dev/null | tr -d '[:space:]')
    if [ -n "$stale_pid" ] && kill -0 "$stale_pid" 2>/dev/null; then
        log "WARNING: Found stale bot process (PID: $stale_pid), sending SIGTERM..."
        kill -TERM "$stale_pid" 2>/dev/null || true
        for i in $(seq 1 30); do
            kill -0 "$stale_pid" 2>/dev/null || break
            sleep 1
        done
        if kill -0 "$stale_pid" 2>/dev/null; then
            log "WARNING: Stale process did not exit after 30s, sending SIGKILL"
            kill -9 "$stale_pid" 2>/dev/null || true
            sleep 2
        fi
        log "Stale process cleaned up"
    fi
    rm -f "$PID_FILE"
fi

WATCHDOG_PID=""
BOT_PID=""
crash_count=0
crash_window_start=$(date +%s)

log "OpenTree wrapper starting (home: $OPENTREE_HOME)"

while true; do
    # -- Crash loop detection (before network wait, so wait time doesn't mask loops) --
    now=$(date +%s)
    if [ $((now - crash_window_start)) -gt $CRASH_WINDOW ]; then
        # Window expired, reset counter
        crash_count=0
        crash_window_start=$now
    fi

    if [ $crash_count -ge $MAX_CRASHES ]; then
        log "CRASH LOOP: $crash_count crashes within ${CRASH_WINDOW}s. Cooling down ${COOLDOWN}s..."
        sleep $COOLDOWN
        crash_count=0
        crash_window_start=$(date +%s)
    fi

    # -- Network check --
    check_network || {
        log "Network unavailable, retrying in 30s..."
        sleep 30
        continue
    }

    # -- Start watchdog --
    start_watchdog

    # -- Start bot (background + wait, so signal trap can respond immediately) --
    log "Starting bot..."
    "${BOT_CMD[@]}" &
    BOT_PID=$!
    echo "$BOT_PID" > "$PID_FILE"
    log "Bot started (PID: $BOT_PID)"

    set +e
    wait "$BOT_PID"
    exit_code=$?
    set -e
    BOT_PID=""

    # -- Cleanup per-run state --
    stop_watchdog
    rm -f "$PID_FILE" "$HEARTBEAT_FILE"

    log "Bot exited (code: $exit_code)"

    # -- Exit code handling --

    # Permanent stop: don't restart
    if [ $exit_code -eq $EXIT_PERMANENT ]; then
        log "Permanent stop requested (exit code $EXIT_PERMANENT). Not restarting."
        break
    fi

    # Clean exit: don't restart
    if [ $exit_code -eq 0 ]; then
        log "Clean exit. Not restarting."
        break
    fi

    # Crash: increment counter, wait, then loop
    crash_count=$((crash_count + 1))
    log "Crash detected ($crash_count/$MAX_CRASHES within window). Restarting in 5s..."
    sleep 5
done

log "Wrapper exiting"
